### ISSUE TITLE
Memory usage in clustering

### ISSUE THREAD

**Issue by MrChenFeng** [srebuffi/lsd-clusters#4]
Thanks for your great work.
I wonder how big ram you used in the clustering step?
![image](https://user-images.githubusercontent.com/24207392/102771297-a969d800-43c0-11eb-8f73-48c534684ee2.png)
There will be ~1TB ram usage in the KNN calculation for example. The PairNum consumes a lot of memory if I'm not wrong.

**Comment by srebuffi** [comment]
Thank you for your question.

For 'feat_row', if the batch size is 256 and the feature size is 512 and we use single precision, the memory size of 'feat_row' should be 256 * 256 * 512 * 4 / (1024 ^ 3) GB = 0.125 GB if I did not do a mistake. So it does not consume too much memory.

Let me know if you do not agree with the formula I used.

**Comment by MrChenFeng** [comment]
Hi rebuffi,

Thanks so much for your reply. You are right, I made a mistake before but I forgot what is the mistake. :p

Best,
Chen
